source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/shvets/Specs.git'

use_frameworks!

target 'Example' do
  platform :ios, '12.2'

  pod 'AudioPlayer', :path => '../'
  pod 'MediaApis', :path => '../../MediaApis'

  podspec :path => 'Example.podspec'

  target 'ExampleTests' do
    inherit! :search_paths
  end
end

#target 'Example_tvOS' do
#  platform :tvos, '10.10'

#  pod 'AudioPlayer', :path => '../'

#  target 'Example_tvOSTests' do
#    inherit! :search_paths
#  end
#end
